routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController as PanelLoginController;

use Illuminate\Support\Facades\Route;
use Telegram\Bot\Laravel\Facades\Telegram;
use App\Http\Controllers\MainController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Telegram routes
Route::post('/' . config('telegram.bot_token') . '/webhook', [MainController::class, 'index']);

Route::get('/test', [MainController::class, 'test']);

Route::get('/set/webhook', function() {
    $response = Telegram::setWebhook([
        'url' => env('APP_URL') . config('telegram.bot_token') . '/webhook'
    ]);

    return $response;
});

Route::get('/remove/webhook', function (){
    $response = Telegram::removeWebhook();

    return $response;
});

Route::redirect('/panel', '/panel/profile/show')->name('panel.main.url');

/** Admin Panel */
Route::get('panel/login', [PanelLoginController::class, 'showPanelLoginForm'])->name('panel.login');

Route::prefix('panel')->middleware(['auth', 'role:admin|manager'])->name('panel.')->group(function ($router) {
    /** Profile */
    $router->prefix('profile')->name('profile.')->group(function ($router) {
        $router->get('show', [ProfileController::class, 'show'])->name('show');
        $router->get('edit', [ProfileController::class, 'edit'])->name('edit');
        $router->put('edit', [ProfileController::class, 'update'])->name('update');
        $router->put('updatePassword', [ProfileController::class, 'updatePassword'])->name('updatePassword');
    });

    /** Users */
    $router->resource('users', UserController::class);
    $router->put('users/{user}/updatePassword', [UserController::class, 'updatePassword'])->name('users.update_password');

    /** Articles */
    $router->resource('articles', ArticlesController::class);

    /** Pages */
    $router->resource('pages', PageController::class, ['except' => ['store', 'create']]);
    $router->post('pages/{page}/worker/add', [PageController::class, 'addWorker'])->name('pages.worker.add');
    $router->post('pages/{page}/worker/{worker}/delete', [PageController::class, 'deleteWorker'])->name('pages.worker.delete');

    /** Workers */
    $router->resource('workers', WorkerController::class);

    /** Orders */
    $router->resource('orders', OrderController::class);

    /** Roles */
    $router->resource('roles', RoleController::class);

    /** Dictionaries */
    $router->resource('dictionaries', DictionaryController::class);

    /** Dictionary Items */
    $router->resource('dictionaries/{dictionary}/items', DictionaryItemController::class, ['names' => 'dictionary-items']);

    /** Membership Applications */
    $router->resource('applications', MembershipApplicationController::class, ['except' => ['store', 'create']]);
    $router->put('applications/{application}/accept', [MembershipApplicationController::class, 'accept'])->name('application.accept');
});

/** General routes */
Route::prefix('')->name('general.')->group(function ($router) {
    $router->get('/', [App\Http\Controllers\General\PageController::class, 'index'])->name('index');
    $router->get('/page/{alias}', [App\Http\Controllers\General\PageController::class, 'view'])->name('page.view');

    $router->get('/analytics', [MainController::class, 'analytics'])->name('analytics');
    $router->get('/analytics-export', [ExportController::class, 'analytics'])->name('analytics-export');

    $router->get('/analytics-sale', [MainController::class, 'analyticsSale'])->name('analytics-sale');
    $router->get('/analytics-sale-export', [ExportController::class, 'analyticsSale'])->name('analytics-sale-export');

    $router->get('/analytics-import', [MainController::class, 'analyticsImport'])->name('analytics-import');
    $router->get('/analytics-import-export', [ExportController::class, 'analyticsImport'])->name('analytics-import-export');

    $router->get('/articles', [MainController::class, 'articles'])->name('articles');
    $router->get('/article/{article}', [MainController::class, 'article'])->name('article.show');
    $router->get('/contact', [App\Http\Controllers\General\PageController::class, 'contact'])->name('contact');

    $router->middleware('auth')->group(function ($router) {
        $router->get('/profile', [MainController::class, 'profile'])->name('profile');
        $router->post('/profile/update', [App\Http\Controllers\General\UserController::class, 'update'])->name('profile-update');
        $router->post('/profile/update-password', [App\Http\Controllers\General\UserController::class, 'updatePassword'])->name('profile-update-password');
    });

    $router->post('/publish-ad', [MainController::class, 'publishAd'])->name('publish-ad');

    /** Auth routes */
    $router->get('/login', [PanelLoginController::class, 'showLoginForm'])->name('show_login');
    $router->post('/login', [PanelLoginController::class, 'login'])->name('login');

    $router->get('/password-recovery', [AuthController::class, 'showPasswordRecoveryForm'])->name('password-recovery');

    $router->get('/registration', [RegisterController::class, 'showRegistrationForm'])->name('registration');
    $router->post('/register', [RegisterController::class, 'register'])->name('register');

    $router->get('/registration-member', [AuthController::class, 'showRegistrationMemberForm'])->name('registration-member');
    $router->post('/register-member', [AuthController::class, 'registerMember'])->name('register-member');

    $router->post('/logout', [LoginController::class, 'logout'])->middleware('auth')->name('logout');
    /** Auth routes */
});

app/Http/Controllers/Admin/WorkerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\WorkerStoreRequest;
use App\Models\Page;
use App\Models\Worker;
use Illuminate\Http\Request;

class WorkerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $workers = Worker::paginate(10);

        return view('admin.pages.worker.index', compact('workers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.pages.worker.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(WorkerStoreRequest $request)
    {
        $validated = $request->validated();

        if ($image = $request->file('image')) {
            $destinationPath = 'upload/images/workers/';
            $profileImage = date('Y-m-d-H-i-s') . "_"  . $image->getClientOriginalName();
            $image->move($destinationPath, $profileImage);
            $validated['image'] = '/' . $destinationPath . $profileImage;
        }

        $worker = Worker::create($validated);

        return redirect()->route('panel.workers.show', $worker->id)->with('success','Сотрудник создан успешно');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Worker $worker)
    {
        return view('admin.pages.worker.show', compact('worker'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Worker $worker)
    {
        return view('admin.pages.worker.edit', compact('worker'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(WorkerStoreRequest $request, Worker $worker)
    {
        $validated = $request->validated();

        if ($image = $request->file('image')) {
            $destinationPath = 'upload/images/workers/';
            $profileImage = date('Y-m-d-H-i-s') . "_"  . $image->getClientOriginalName();
            $image->move($destinationPath, $profileImage);
            $validated['image'] = '/' . $destinationPath . $profileImage;
        }

        $worker->update($validated);

        return redirect()->route('panel.workers.show', $worker->id)->with('success','Сотрудник обновлен успешно');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Worker $worker)
    {
        $worker->forceDelete();

        return redirect( route('panel.workers.index'))->with('success', 'Сотрудник успешно удален');
    }
}

resources/views/admin/pages/worker/create.blade.php
@extends('admin.layouts.index')

@section('title', 'Сотрудники')

@section('content')

<div class="container container-fluid">
    <div class="title-block">
        <div class="row row--multiline align-items-center">
            <div class="col-md-8">
                <ul class="breadcrumbs">
                    <li><a href="{{ route('panel.workers.index') }}">Соторудники</a></li>
                    <li><span>Добавить</span></li>
                </ul>
            </div>
            <div class="col-md-4 text-right-md text-right-lg">
                <div class="flex-form">
                    <div class="pull-right">
{{--                        <a class="btn btn-primary" href="{{ route('panel.workers.index') }}">Назад</a>--}}
                    </div>
                </div>
            </div>
        </div>
    </div>

    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="block">
        @can('worker-create')
        <form method="post" action="{{route('panel.workers.store') }}" enctype="multipart/form-data">
            @csrf
            <h2 class="title-primary">Соторудник</h2>
            <div class="input-group">
                <label class="input-group__title">ФИО (РУС)<span class="required">*</span></label>
                <input type="text" name="name_ru" placeholder="Название" class="input-regular" required>
            </div>
            <div class="input-group">
                <label class="input-group__title">Должность (РУС)<span class="required">*</span></label>
                <input type="text" name="position_ru" placeholder="Название" class="input-regular" required>
            </div>
            <br>
            <div class="input-group">
                <label class="input-group__title">ТАӘ (ҚАЗ)<span class="required">*</span></label>
                <input type="text" name="name_kk" placeholder="Название" class="input-regular" required>
            </div>
            <br>
            <div class="input-group">
                <label class="input-group__title">Лауазымы (ҚАЗ)<span class="required">*</span></label>
                <input type="text" name="position_kk" placeholder="Название" class="input-regular" required>
            </div>
            <br>
            <div class="input-group">
                <label class="input-group__title">Full name (ENG)<span class="required">*</span></label>
                <input type="text" name="name_en" placeholder="Название" class="input-regular" required>
            </div>
            <br>
            <div class="input-group">
                <label class="input-group__title">Position (ENG)<span class="required">*</span></label>
                <input type="text" name="position_en" placeholder="Название" class="input-regular" required>
            </div>
            <br>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <label class="input-group__title">Фото</label>
                    <input type="file" name="image" class="form-control" placeholder="image">
                </div>
            </div>
            <br>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Сохранить</button>
            </div>
        </form>
        @endcan
    </div>
</div>

@endsection
@section('scripts')
    <!--Only this page's scripts-->
    <!---->
@endsection

resources/views/admin/pages/worker/edit.blade.php
@extends('admin.layouts.index')

@section('title', 'Сотрудники')

@section('content')

<div class="container container-fluid">
    <div class="title-block">
        <div class="row row--multiline align-items-center">
            <div class="col-md-8">
                <ul class="breadcrumbs">
                    <li><a href="{{ route('panel.workers.index') }}">Соторудники</a></li>
                    <li><a href="{{ route('panel.workers.show', $worker->id) }}">{{ $worker->name }}</a></li>
                    <li><span>{{ $worker->name }}</span></li>
                    <li><span>Редактировать</span></li>
                </ul>
            </div>
            <div class="col-md-4 text-right-md text-right-lg">
                <div class="flex-form">
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ route('panel.dictionaries.index') }}">Назад</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="block">
        <form method="post" action="{{route('panel.workers.update', $worker) }}" enctype="multipart/form-data">
            @csrf
            @method('put')
            <h2 class="title-primary">Словарь</h2>
            <div class="input-group">
                <label class="input-group__title">Название (РУС)<span class="required">*</span></label>
                <input type="text" name="name_ru" placeholder="Название" class="input-regular" value="{{ $worker->name_ru }}" required>
            </div>
            <br>
            <div class="input-group">
                <label class="input-group__title">Должность (РУС)<span class="required">*</span></label>
                <input type="text" name="position_ru" placeholder="Название" class="input-regular" value="{{ $worker->position_ru }}"required>
            </div>
            <br>
            <div class="input-group">
                <label class="input-group__title">Название (ҚАЗ)<span class="required">*</span></label>
                <input type="text" name="name_kk" placeholder="Название" class="input-regular" value="{{ $worker->name_kk }}" required>
            </div>
            <br>
            <div class="input-group">
                <label class="input-group__title">Лауазымы (ҚАЗ)<span class="required">*</span></label>
                <input type="text" name="position_kk" placeholder="Название" class="input-regular" value="{{ $worker->position_kk }}" required>
            </div>
            <br>
            <div class="input-group">
                <label class="input-group__title">Название (ENG)<span class="required">*</span></label>
                <input type="text" name="name_en" placeholder="Название" class="input-regular" value="{{ $worker->name_en }}" required>
            </div>
            <br>
            <div class="input-group">
                <label class="input-group__title">Position (ENG)<span class="required">*</span></label>
                <input type="text" name="position_en" placeholder="Название" class="input-regular" value="{{ $worker->position_en }}"required>
            </div>
            <br>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <label class="input-group__title">Фото</label>
                    <input type="file" name="image" class="form-control" placeholder="image">
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    <button type="submit" class="btn btn--green">Сохранить</button>
                    @can('worker-delete')
                        <a class="btn btn-danger btn--red" href="{{ route('panel.workers.destroy', $worker->id) }}"
                           onclick="event.preventDefault();
                                                     document.getElementById('delete-form').submit();" title="Удалить">Удалить
                        </a>
                    @endcan
                </div>
            </div>
        </form>
        @can('order-delete')
            <form id="delete-form" action="{{ route('panel.workers.destroy', $worker->id) }}" method="POST" class="d-none">
                @csrf
                @method('DELETE')
            </form>
        @endcan
    </div>
</div>

@endsection
@section('scripts')
    <!--Only this page's scripts-->
    <!---->
@endsection

resources/views/admin/pages/worker/index.blade.php
@extends('admin.layouts.index')

@section('title', 'Сотрудники')

@section('content')

<div class="container container-fluid">
    <div class="title-block">
        <div class="row row--multiline align-items-center">
            <div class="col-md-8">
                <h1 class="title-primary" style="margin-bottom: 0">Управление сотрудниками</h1>
            </div>
            <div class="col-md-4 text-right-md text-right-lg">
                <div class="flex-form">
                    <div>
                        @can('worker-create')
                            <a class="btn btn-success" href="{{ route('panel.workers.create') }}">Добавить сотрудника</a>
                        @endcan
                    </div>
                </div>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <br>
    <div class="block">
        <h2 class="title-secondary">Список новостей</h2>
        <table class="table table-records">
            <colgroup>
                <col span="1" style="width: 3%;">
                <col span="1" style="width: 20%;">
                <col span="1" style="width: 30%;">
                <col span="1" style="width: 30%;">
            </colgroup>
            <thead>
                <tr>
                    <th>No</th>
                    <th>ФИО</th>
                    <th>Должность</th>
                    <th>Действие</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($workers as $worker)
                    <tr>
                        <td>{{ $worker->id }}</td>
                        <td>{{ $worker->name_ru }}</td>
                        <td>{{ $worker->position_ru }}</td>
                        <td>
                            <a class="icon-btn icon-btn--green icon-eye" href="{{ route('panel.workers.show', $worker->id) }}" title="Смотреть"></a>
                            @can('worker-edit')
                                <a class="icon-btn icon-btn--yellow icon-edit" href="{{ route('panel.workers.edit', $worker->id) }}" title="Редактировать"></a>
                            @endcan
                            @can('worker-delete')
                                <a href="javascript:;" title="Удалить"
                                   onclick="document.querySelector('#model-{{ $worker->id }}').submit()"
                                   class="icon-btn icon-btn--pink icon-delete"></a>
                                <form action="{{ route('panel.workers.destroy',  $worker->id) }}" id="model-{{ $worker->id }}" method="post">
                                    @csrf
                                    @method('DELETE')
                                </form>
                            @endcan
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        {{ $workers->appends(\Illuminate\Support\Facades\Request::except('page'))->links("vendor.pagination.admin") }}
    </div>
</div>

@endsection
@section('scripts')
    <!--Only this page's scripts-->
    <!---->
@endsection

resources/views/admin/pages/worker/show.blade.php
@extends('admin.layouts.index')

@section('title', 'Сотрудники')

@section('content')

<div class="container container-fluid">
    <div class="title-block">
        <div class="row row--multiline align-items-center">
            <div class="col-md-8">
                <ul class="breadcrumbs">
                    <li><a href="{{ route('panel.workers.index') }}">Сотрудники</a></li>
                    <li><span>{{ $worker->name }}</span></li>
                </ul>
            </div>
            <div class="col-md-4 text-right-md text-right-lg">
                <div class="flex-form">
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ route('panel.workers.index') }}">Назад</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <div class="block">
        <h2 class="title-primary">Сотрудник</h2>
        <div class="input-group">
            <div class="input-group__title">Фотограция</div>
            <a href="{{ $worker->image }}" target="_blank">
                <img class="article-image" src="{{ $worker->image ?? ''}}" height="200" width="400">
            </a>
        </div>
        <div class="input-group">
            <label class="input-group__title">ФИО (РУС)</label>
            <input type="text" name="name_ru" placeholder="Название" class="input-regular" value="{{ $worker->name_ru }}" disabled>
        </div>
        <br>
        <div class="input-group">
            <label class="input-group__title">Должность (РУС)</label>
            <input type="text" name="position_ru" placeholder="Должность" class="input-regular" value="{{ $worker->position_ru }}" disabled>
        </div>
        <br>
        <div class="input-group">
            <label class="input-group__title">ТАӘ (ҚАЗ)</label>
            <input type="text" name="name_kk" placeholder="Название" class="input-regular" value="{{ $worker->name_kk }}" disabled>
        </div>
        <br>
        <div class="input-group">
            <label class="input-group__title">Лауазым (ҚАЗ)</label>
            <input type="text" name="position_kk" placeholder="Лауазым" class="input-regular" value="{{ $worker->position_kk }}" disabled>
        </div>
        <br>
        <div class="input-group">
            <label class="input-group__title">Full name (ENG)</label>
            <input type="text" name="name_en" placeholder="Название" class="input-regular" value="{{ $worker->name_en }}" disabled>
        </div>
        <br>
        <div class="input-group">
            <label class="input-group__title">Position (ENG)</label>
            <input type="text" name="position_en" placeholder="Position" class="input-regular" value="{{ $worker->position_en }}" disabled>
        </div>
        <br>
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                @can('worker-edit')
                    <a class="btn btn-primary" href="{{ route('panel.workers.edit', $worker->id) }}">Редактировать</a>
                @endcan
                @can('worker-delete')
                    <a class="btn btn-danger btn--red" href="{{ route('panel.workers.destroy', $worker->id) }}"
                       onclick="event.preventDefault();
                                                     document.getElementById('delete-form').submit();" title="Удалить"">Удалить
                    </a>
                    <form id="delete-form" action="{{ route('panel.workers.destroy', $worker->id) }}" method="POST" class="d-none">
                        @csrf
                        @method('DELETE')
                    </form>
                @endcan
            </div>
        </div>
    </div>
</div>

@endsection
@section('scripts')
    <!--Only this page's scripts-->
    <!---->
@endsection