routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController as PanelLoginController;

use Illuminate\Support\Facades\Route;
use Telegram\Bot\Laravel\Facades\Telegram;
use App\Http\Controllers\MainController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Telegram routes
Route::post('/' . config('telegram.bot_token') . '/webhook', [MainController::class, 'index']);

Route::get('/test', [MainController::class, 'test']);

Route::get('/set/webhook', function() {
    $response = Telegram::setWebhook([
        'url' => env('APP_URL') . config('telegram.bot_token') . '/webhook'
    ]);

    return $response;
});

Route::get('/remove/webhook', function (){
    $response = Telegram::removeWebhook();

    return $response;
});

Route::redirect('/panel', '/panel/profile/show')->name('panel.main.url');

/** Admin Panel */
Route::get('panel/login', [PanelLoginController::class, 'showPanelLoginForm'])->name('panel.login');

Route::prefix('panel')->middleware(['auth', 'role:admin|manager'])->name('panel.')->group(function ($router) {
    /** Profile */
    $router->prefix('profile')->name('profile.')->group(function ($router) {
        $router->get('show', [ProfileController::class, 'show'])->name('show');
        $router->get('edit', [ProfileController::class, 'edit'])->name('edit');
        $router->put('edit', [ProfileController::class, 'update'])->name('update');
        $router->put('updatePassword', [ProfileController::class, 'updatePassword'])->name('updatePassword');
    });

    /** Users */
    $router->resource('users', UserController::class);
    $router->put('users/{user}/updatePassword', [UserController::class, 'updatePassword'])->name('users.update_password');

    /** Articles */
    $router->resource('articles', ArticlesController::class);

    /** Pages */
    $router->resource('pages', PageController::class, ['except' => ['store', 'create']]);
    $router->post('pages/{page}/worker/add', [PageController::class, 'addWorker'])->name('pages.worker.add');
    $router->post('pages/{page}/worker/{worker}/delete', [PageController::class, 'deleteWorker'])->name('pages.worker.delete');

    /** Workers */
    $router->resource('workers', WorkerController::class);

    /** Orders */
    $router->resource('orders', OrderController::class);

    /** Roles */
    $router->resource('roles', RoleController::class);

    /** Dictionaries */
    $router->resource('dictionaries', DictionaryController::class);

    /** Dictionary Items */
    $router->resource('dictionaries/{dictionary}/items', DictionaryItemController::class, ['names' => 'dictionary-items']);

    /** Membership Applications */
    $router->resource('applications', MembershipApplicationController::class, ['except' => ['store', 'create']]);
    $router->put('applications/{application}/accept', [MembershipApplicationController::class, 'accept'])->name('application.accept');
});

/** General routes */
Route::prefix('')->name('general.')->group(function ($router) {
    $router->get('/', [App\Http\Controllers\General\PageController::class, 'index'])->name('index');
    $router->get('/page/{alias}', [App\Http\Controllers\General\PageController::class, 'view'])->name('page.view');

    $router->get('/analytics', [MainController::class, 'analytics'])->name('analytics');
    $router->get('/analytics-export', [ExportController::class, 'analytics'])->name('analytics-export');

    $router->get('/analytics-sale', [MainController::class, 'analyticsSale'])->name('analytics-sale');
    $router->get('/analytics-sale-export', [ExportController::class, 'analyticsSale'])->name('analytics-sale-export');

    $router->get('/analytics-import', [MainController::class, 'analyticsImport'])->name('analytics-import');
    $router->get('/analytics-import-export', [ExportController::class, 'analyticsImport'])->name('analytics-import-export');

    $router->get('/articles', [MainController::class, 'articles'])->name('articles');
    $router->get('/article/{article}', [MainController::class, 'article'])->name('article.show');
    $router->get('/contact', [App\Http\Controllers\General\PageController::class, 'contact'])->name('contact');

    $router->middleware('auth')->group(function ($router) {
        $router->get('/profile', [MainController::class, 'profile'])->name('profile');
        $router->post('/profile/update', [App\Http\Controllers\General\UserController::class, 'update'])->name('profile-update');
        $router->post('/profile/update-password', [App\Http\Controllers\General\UserController::class, 'updatePassword'])->name('profile-update-password');
    });

    $router->post('/publish-ad', [MainController::class, 'publishAd'])->name('publish-ad');

    /** Auth routes */
    $router->get('/login', [PanelLoginController::class, 'showLoginForm'])->name('show_login');
    $router->post('/login', [PanelLoginController::class, 'login'])->name('login');

    $router->get('/password-recovery', [AuthController::class, 'showPasswordRecoveryForm'])->name('password-recovery');

    $router->get('/registration', [RegisterController::class, 'showRegistrationForm'])->name('registration');
    $router->post('/register', [RegisterController::class, 'register'])->name('register');

    $router->get('/registration-member', [AuthController::class, 'showRegistrationMemberForm'])->name('registration-member');
    $router->post('/register-member', [AuthController::class, 'registerMember'])->name('register-member');

    $router->post('/logout', [LoginController::class, 'logout'])->middleware('auth')->name('logout');
    /** Auth routes */
});

resources/views/admin/pages/page/edit.blade.php
@extends('admin.layouts.index')

@section('title', 'Страницы')

@section('content')

<div class="container container-fluid">
    <div class="title-block">
        <div class="row row--multiline align-items-center">
            <div class="col-md-8">
                <ul class="breadcrumbs">
                    <li><a href="{{ route('panel.pages.index') }}">Управление страницами</a></li>
                    <li><a href="{{ route('panel.pages.show', $page) }}">{{ $page->title }}</a></li>
                    <li><span>Редактировать</span></li>
                </ul>
            </div>
            <div class="col-md-4 text-right-md text-right-lg">
                <div class="flex-form">
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ route('panel.pages.index') }}">Назад</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="block">
        <form method="post" action="{{route('panel.pages.update', $page) }}" enctype="multipart/form-data">
            @csrf
            @method('put')

            <h2 class="title-primary">Новость</h2>
            <div class="tabs">
                <div class="mobile-dropdown">
                    <div class="mobile-dropdown__title dynamic">Рус</div>
                    <div class="mobile-dropdown__desc">
                        <ul class="tabs-titles">
                            <li class="active"><a href="javascript:;" title="Рус">Рус</a></li>
                            <li><a href="javascript:;" id="" title="Қаз">Қаз</a></li>
                            <li><a href="javascript:;" id="" title="Қаз">Eng</a></li>
                        </ul>
                    </div>
                </div>
                <div class="tabs-contents">
                    <div class="active">
                        <div class="input-group">
                            <label class="input-group__title">Название <span class="required">*</span></label>
                            <input type="text" name="title_ru" placeholder="Название" class="input-regular" value="{{ $page->title_ru }}">
                        </div>
                        <br>
                        <div class="input-group">
                            <div class="input-group__title">Описание <span class="required">*</span></div>
                            <textarea name="description_ru" class="tinymce-here input-regular" >{!! $page->description_ru !!}</textarea>
                        </div>
                        <br>
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <label class="input-group__title">Фото</label>
                                <input type="file" name="image_ru" class="form-control" placeholder="image">
                            </div>
                        </div>
                    </div>
                    <div>
                        <div class="input-group">
                            <label class="input-group__title">Атауы <span class="required">*</span></label>
                            <input type="text" name="title_kk" placeholder="Название" class="input-regular" value="{{ $page->title_kk }}">
                        </div>
                        <br>
                        <div class="input-group">
                            <div class="input-group__title">Сипаттамасы <span class="required">*</span></div>
                            <textarea name="description_kk" class="tinymce-here input-regular">{!! $page->description_kk !!}</textarea>
                        </div>
                        <br>
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <label class="input-group__title">Фото</label>
                                <input type="file" name="image_kk" class="form-control" placeholder="image">
                            </div>
                        </div>
                    </div>
                    <div>
                        <div class="input-group">
                            <label class="input-group__title">Title <span class="required">*</span></label>
                            <input type="text" name="title_en" placeholder="Название" class="input-regular" value="{{ $page->title_en }}">
                        </div>
                        <br>
                        <div class="input-group">
                            <div class="input-group__title">Description <span class="required">*</span></div>
                            <textarea name="description_en" class="tinymce-here input-regular">{!! $page->description_en !!}</textarea>
                        </div>
                        <br>
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <label class="input-group__title">Image</label>
                                <input type="file" name="image_en" class="form-control" placeholder="image">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    <button type="submit" class="btn btn--green">Сохранить</button>
{{--                    @can('page-delete')--}}
{{--                        <a class="btn btn-danger btn--red" href="{{ route('panel.pages.destroy', $page->id) }}"--}}
{{--                           onclick="event.preventDefault();--}}
{{--                                                         document.getElementById('delete-form').submit();" title="Удалить">Удалить--}}
{{--                        </a>--}}
{{--                    @endcan--}}
                </div>
            </div>
        </form>
        <br>
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
{{--            @can('page-delete')--}}
{{--                <form id="delete-form" action="{{ route('panel.pages.destroy', $page->id) }}" method="POST" class="d-none">--}}
{{--                    @csrf--}}
{{--                    @method('DELETE')--}}
{{--                </form>--}}
{{--            @endcan--}}
            </div>
        </div>
    </div>
</div>

@endsection
@section('scripts')
    <!--Only this page's scripts-->
    <script src="https://cdn.tiny.cloud/1/eutvjr9zyhc4qtchwyfwhutknw2iunsf80kiuye2fdomu2wd/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="/admin/js/api.js"></script>
    <script src="/admin/js/tinymce.js"></script>
    <!---->
@endsection

resources/views/admin/pages/page/index.blade.php
@extends('admin.layouts.index')

@section('title', 'Страницы')

@section('content')

<div class="container container-fluid">
    <div class="title-block">
        <div class="row row--multiline align-items-center">
            <div class="col-md-8">
                <h1 class="title-primary" style="margin-bottom: 0">Управление страницами</h1>
            </div>
            <div class="col-md-4 text-right-md text-right-lg">
                <div class="flex-form">
                    <div>
{{--                        @can('page-create')--}}
{{--                            <a class="btn btn-success" href="{{ route('panel.articles.create') }}">Добавить новость</a>--}}
{{--                        @endcan--}}
                    </div>
                </div>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <br>
    <div class="block">
        <h2 class="title-secondary">Список страниц</h2>
        <table class="table table-records">
            <colgroup>
                <col span="1" style="width: 3%;">
                <col span="1" style="width: 22%;">
                <col span="1" style="width: 22%;">
                <col span="1" style="width: 22%;">
                <col span="1" style="width: 25%;">
            </colgroup>
            <thead>
                <tr>
                    <th>No</th>
                    <th>Название (РУС)</th>
                    <th>Название (ҚАЗ)</th>
                    <th>Название (ENG)</th>
                    <th>Действие</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($pages as $page)
                    <tr>
                        <td>{{ $page->id }}</td>
                        <td>{{ $page->title_ru }}</td>
                        <td>{{ $page->title_kk }}</td>
                        <td>{{ $page->title_en }}</td>
                        <td>
                            <a class="icon-btn icon-btn--green icon-eye" href="{{ route('panel.pages.show', $page->id) }}" title="Смотреть"></a>
                            @can('page-edit')
                                <a class="icon-btn icon-btn--yellow icon-edit" href="{{ route('panel.pages.edit', $page->id) }}" title="Редактировать"></a>
                            @endcan
{{--                            @can('page-delete')--}}
{{--                                <a href="javascript:;" title="Удалить"--}}
{{--                                   onclick="document.querySelector('#model-{{ $page->id }}').submit()"--}}
{{--                                   class="icon-btn icon-btn--pink icon-delete"></a>--}}
{{--                                <form action="{{ route('panel.pages.destroy',  $page->id) }}" id="model-{{ $page->id }}" method="post">--}}
{{--                                    @csrf--}}
{{--                                    @method('DELETE')--}}
{{--                                </form>--}}
{{--                            @endcan--}}
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        {{ $pages->appends(\Illuminate\Support\Facades\Request::except('page'))->links("vendor.pagination.admin") }}
    </div>
</div>

@endsection
@section('scripts')
    <!--Only this page's scripts-->
    <!---->
@endsection

resources/views/admin/pages/page/show.blade.php
@extends('admin.layouts.index')

@section('title', 'Страницы')

@section('content')

<div class="container container-fluid">
    <div class="title-block">
        <div class="row row--multiline align-items-center">
            <div class="col-md-8">
                <ul class="breadcrumbs">
                    <li><a href="{{ route('panel.pages.index') }}">Управление страницами</a></li>
                    <li><span>{{ $page->title }}</span></li>
                </ul>
            </div>
            <div class="col-md-4 text-right-md text-right-lg">
                <div class="flex-form">
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ route('panel.pages.index') }}">Назад</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <div class="block">
        <h2 class="title-primary">Страница</h2>
        <div class="tabs">
            <div class="mobile-dropdown">
                <div class="mobile-dropdown__title dynamic">Рус</div>
                <div class="mobile-dropdown__desc">
                    <ul class="tabs-titles">
                        <li class="active"><a href="javascript:;" title="Рус">Рус</a></li>
                        <li><a href="javascript:;" id="" title="Қаз">Қаз</a></li>
                        <li><a href="javascript:;" id="" title="Қаз">Eng</a></li>
                    </ul>
                </div>
            </div>
            <div class="tabs-contents">
                <div class="active">
                    <div class="input-group">
                        <label class="input-group__title">Название</label>
                        <input type="text" name="title_ru" placeholder="Название" class="input-regular" value="{{ $page->title_ru }}" disabled>
                    </div>
                    <div class="input-group">
                        <div class="input-group__title">Описание</div>
                        <textarea name="description_ru" class="tinymce-text-here input-regular" disabled>{!! $page->description_ru !!}</textarea>
                    </div>
                </div>
                <div>
                    <div class="input-group">
                        <label class="input-group__title">Атауы</label>
                        <input type="text" name="title_kk" placeholder="Название" class="input-regular" value="{{ $page->title_kk }}" disabled>
                    </div>
                    <div class="input-group">
                        <div class="input-group__title">Сипаттамасы</div>
                        <textarea name="description_kk" class="tinymce-text-here input-regular" disabled>{!! $page->description_kk !!}</textarea>
                    </div>
                </div>
                <div>
                    <div class="input-group">
                        <label class="input-group__title">Title</label>
                        <input type="text" name="title_en" placeholder="Название" class="input-regular" value="{{ $page->title_en }}" disabled>
                    </div>
                    <div class="input-group">
                        <div class="input-group__title">Description</div>
                        <textarea name="description_en" class="tinymce-text-here input-regular" disabled>{!! $page->description_en !!}</textarea>
                    </div>
                </div>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                @can('page-edit')
                    <a class="btn btn-primary" href="{{ route('panel.pages.edit', $page->id) }}" title="Редактировать">Редактировать</a>
                @endcan
{{--                @can('page-delete')--}}
{{--                    <a class="btn btn-danger btn--red" href="{{ route('panel.pages.destroy', $page->id) }}"--}}
{{--                       onclick="event.preventDefault();--}}
{{--                                                 document.getElementById('delete-form').submit();" title="Удалить">Удалить--}}
{{--                    </a>--}}
{{--                    <form id="delete-form" action="{{ route('panel.pages.destroy', $page->id) }}" method="POST" class="d-none">--}}
{{--                        @csrf--}}
{{--                        @method('DELETE')--}}
{{--                    </form>--}}
{{--                @endcan--}}
            </div>
        </div>
    </div>

    <form class="block" method="post" action="{{ route('panel.pages.worker.add', $page->id) }}">
        @csrf
        @method('post')

        <div class="row">
            <div class="col-xs-8 col-sm-8 col-md-8">
                <div class="input-group">
                    <label class="input-group__title">Добавить сотрудника</label>
                    <select name="worker_ids[]" class="chosen no-search input-regular" data-placeholder="Выберите сотрудника" required multiple>
                        <option value="" disabled>Выберите сотрудника</option>
                        @forelse($allWorkers as $worker)
                            <option value="{{ $worker->id }}">{{ $worker->name_ru }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="col-xs-4 col-sm-4 col-md-4">
                <br>
                <button type="submit" class="btn btn--green">Добавить</button>
            </div>
        </div>
    </form>

    <div class="block">
        <h2 class="title-secondary">Список сотрудников</h2>
        <table class="table table-records">
            <colgroup>
                <col span="1" style="width: 3%;">
                <col span="1" style="width: 22%;">
                <col span="1" style="width: 22%;">
                <col span="1" style="width: 25%;">
            </colgroup>
            <thead>
            <tr>
                <th>No</th>
                <th>ФИО</th>
                <th>Должность</th>
                <th>Действие</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($workers as $worker)
                <tr>
                    <td>{{ $worker->id }}</td>
                    <td>{{ $worker->name_ru }}</td>
                    <td>{{ $worker->position_ru }}</td>
                    <td>
                        <a class="icon-btn icon-btn--green icon-eye" href="{{ route('panel.workers.show', $worker->id) }}" title="Смотреть"></a>
                        @can('worker-edit')
                            <a class="icon-btn icon-btn--yellow icon-edit" href="{{ route('panel.workers.edit', $worker->id) }}" title="Редактировать"></a>
                            <a href="javascript:;" title="Удалить"
                               onclick="document.querySelector('#model-{{ $worker->id }}').submit()"
                               class="btn btn-danger btn--red">Удалить</a>
                            <form action="{{ route('panel.pages.worker.delete', [$page->id, $worker->id]) }}" id="model-{{ $worker->id }}" method="post">
                                @csrf
                            </form>
                        @endcan
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>

        {{ $workers->appends(\Illuminate\Support\Facades\Request::except('page'))->links("vendor.pagination.admin") }}
    </div>
</div>

@endsection
@section('scripts')
    <!--Only this page's scripts-->
    <!---->
@endsection