routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController as PanelLoginController;

use Illuminate\Support\Facades\Route;
use Telegram\Bot\Laravel\Facades\Telegram;
use App\Http\Controllers\MainController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Telegram routes
Route::post('/' . config('telegram.bot_token') . '/webhook', [MainController::class, 'index']);

Route::get('/test', [MainController::class, 'test']);

Route::get('/set/webhook', function() {
    $response = Telegram::setWebhook([
        'url' => env('APP_URL') . config('telegram.bot_token') . '/webhook'
    ]);

    return $response;
});

Route::get('/remove/webhook', function (){
    $response = Telegram::removeWebhook();

    return $response;
});

Route::redirect('/panel', '/panel/profile/show')->name('panel.main.url');

/** Admin Panel */
Route::get('panel/login', [PanelLoginController::class, 'showPanelLoginForm'])->name('panel.login');

Route::prefix('panel')->middleware(['auth', 'role:admin|manager'])->name('panel.')->group(function ($router) {
    /** Profile */
    $router->prefix('profile')->name('profile.')->group(function ($router) {
        $router->get('show', [ProfileController::class, 'show'])->name('show');
        $router->get('edit', [ProfileController::class, 'edit'])->name('edit');
        $router->put('edit', [ProfileController::class, 'update'])->name('update');
        $router->put('updatePassword', [ProfileController::class, 'updatePassword'])->name('updatePassword');
    });

    /** Users */
    $router->resource('users', UserController::class);
    $router->put('users/{user}/updatePassword', [UserController::class, 'updatePassword'])->name('users.update_password');

    /** Articles */
    $router->resource('articles', ArticlesController::class);

    /** Pages */
    $router->resource('pages', PageController::class, ['except' => ['store', 'create']]);
    $router->post('pages/{page}/worker/add', [PageController::class, 'addWorker'])->name('pages.worker.add');
    $router->post('pages/{page}/worker/{worker}/delete', [PageController::class, 'deleteWorker'])->name('pages.worker.delete');

    /** Workers */
    $router->resource('workers', WorkerController::class);

    /** Orders */
    $router->resource('orders', OrderController::class);

    /** Roles */
    $router->resource('roles', RoleController::class);

    /** Dictionaries */
    $router->resource('dictionaries', DictionaryController::class);

    /** Dictionary Items */
    $router->resource('dictionaries/{dictionary}/items', DictionaryItemController::class, ['names' => 'dictionary-items']);

    /** Membership Applications */
    $router->resource('applications', MembershipApplicationController::class, ['except' => ['store', 'create']]);
    $router->put('applications/{application}/accept', [MembershipApplicationController::class, 'accept'])->name('application.accept');
});

/** General routes */
Route::prefix('')->name('general.')->group(function ($router) {
    $router->get('/', [App\Http\Controllers\General\PageController::class, 'index'])->name('index');
    $router->get('/page/{alias}', [App\Http\Controllers\General\PageController::class, 'view'])->name('page.view');

    $router->get('/analytics', [MainController::class, 'analytics'])->name('analytics');
    $router->get('/analytics-export', [ExportController::class, 'analytics'])->name('analytics-export');

    $router->get('/analytics-sale', [MainController::class, 'analyticsSale'])->name('analytics-sale');
    $router->get('/analytics-sale-export', [ExportController::class, 'analyticsSale'])->name('analytics-sale-export');

    $router->get('/analytics-import', [MainController::class, 'analyticsImport'])->name('analytics-import');
    $router->get('/analytics-import-export', [ExportController::class, 'analyticsImport'])->name('analytics-import-export');

    $router->get('/articles', [MainController::class, 'articles'])->name('articles');
    $router->get('/article/{article}', [MainController::class, 'article'])->name('article.show');
    $router->get('/contact', [App\Http\Controllers\General\PageController::class, 'contact'])->name('contact');

    $router->middleware('auth')->group(function ($router) {
        $router->get('/profile', [MainController::class, 'profile'])->name('profile');
        $router->post('/profile/update', [App\Http\Controllers\General\UserController::class, 'update'])->name('profile-update');
        $router->post('/profile/update-password', [App\Http\Controllers\General\UserController::class, 'updatePassword'])->name('profile-update-password');
    });

    $router->post('/publish-ad', [MainController::class, 'publishAd'])->name('publish-ad');

    /** Auth routes */
    $router->get('/login', [PanelLoginController::class, 'showLoginForm'])->name('show_login');
    $router->post('/login', [PanelLoginController::class, 'login'])->name('login');

    $router->get('/password-recovery', [AuthController::class, 'showPasswordRecoveryForm'])->name('password-recovery');

    $router->get('/registration', [RegisterController::class, 'showRegistrationForm'])->name('registration');
    $router->post('/register', [RegisterController::class, 'register'])->name('register');

    $router->get('/registration-member', [AuthController::class, 'showRegistrationMemberForm'])->name('registration-member');
    $router->post('/register-member', [AuthController::class, 'registerMember'])->name('register-member');

    $router->post('/logout', [LoginController::class, 'logout'])->middleware('auth')->name('logout');
    /** Auth routes */
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\App;
use Spatie\Translatable\HasTranslations;

/**
 * App\Category
 *
 * @method static \Illuminate\Database\Eloquent\Builder|Category newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Category newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Category query()
 * @mixin \Eloquent
 * @property int $id
 * @property array $name
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read array $translations
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\SubCategory[] $subCategories
 * @property-read int|null $sub_categories_count
 * @method static \Illuminate\Database\Eloquent\Builder|Category whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Category whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Category whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Category whereUpdatedAt($value)
 * @property string $title_en
 * @property string $title_ru
 * @property string $title_kk
 * @property-read mixed $title
 * @method static \Illuminate\Database\Eloquent\Builder|Category whereTitleEn($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Category whereTitleKk($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Category whereTitleRu($value)
 */
class Category extends Model
{
    public function subCategories()
    {
        return $this->hasMany(SubCategory::class);
    }

    public function getTitleAttribute()
    {
        $title = 'title_' . App::getLocale();
        return $this->$title;
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Http\Controllers\Controller;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Redirector;
use Illuminate\View\View;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        $categories = Category::paginate(10);

        return view('admin.pages.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        return view('admin.pages.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return RedirectResponse
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'title_en' => 'required',
            'title_ru' => 'required',
            'title_kk' => 'required',
        ]);

        $category = Category::create($validated);

        return redirect()->route('panel.categories.show', $category)->with('success','Category created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param Category $category
     * @return Application|Factory|View
     */
    public function show(Category $category)
    {
        return view('admin.pages.categories.show', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Category $category
     * @return Application|Factory|View
     */
    public function edit(Category $category)
    {
        return view('admin.pages.categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Category $category
     * @return RedirectResponse
     */
    public function update(Request $request, Category $category)
    {
        $validated = $request->validate([
            'title' => 'required',
            'description' => 'required',
        ]);

        $category->update($validated);

        return redirect()->route('panel.categories.show', $category)->with('success','Category updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Category $category
     * @return Application|RedirectResponse|Redirector
     */
    public function destroy(Category $category)
    {
        $category->forceDelete();

        return redirect()->route('admin.pages.categories.index')->with('success','Post deleted successfully');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        //
    }
}

resources/views/admin/pages/categories/edit.blade.php
@extends('admin.layouts.index')

@section('title', 'Новости')

@section('content')

<div class="container container-fluid">
    <div class="title-block">
        <div class="row row--multiline align-items-center">
            <div class="col-md-8">
                <ul class="breadcrumbs">
                    <li><a href="{{ route('panel.articles.index') }}">Управление новостями</a></li>
                    <li><a href="{{ route('panel.articles.show', $article) }}">{{ $article->title }}</a></li>
                    <li><span>Редактировать</span></li>
                </ul>
            </div>
            <div class="col-md-4 text-right-md text-right-lg">
                <div class="flex-form">
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ route('panel.articles.index') }}">Назад</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="block">
        <form method="post" action="{{route('panel.articles.update', $article) }}" enctype="multipart/form-data">
            @csrf
            @method('put')

            <h2 class="title-primary">Новость</h2>
            <div class="tabs">
                <div class="mobile-dropdown">
                    <div class="mobile-dropdown__title dynamic">Рус</div>
                    <div class="mobile-dropdown__desc">
                        <ul class="tabs-titles">
                            <li class="active"><a href="javascript:;" title="Рус">Рус</a></li>
                            <li><a href="javascript:;" id="" title="Қаз">Қаз</a></li>
                            <li><a href="javascript:;" id="" title="Қаз">Eng</a></li>
                        </ul>
                    </div>
                </div>
                <div class="tabs-contents">
                    <div class="active">
                        <div class="input-group">
                            <label class="input-group__title">Название <span class="required">*</span></label>
                            <input type="text" name="title_ru" placeholder="Название" class="input-regular" value="{{ $article->title_ru }}">
                        </div>
                        <br>
                        <div class="input-group">
                            <div class="input-group__title">Описание <span class="required">*</span></div>
                            <textarea name="description_ru" class="tinymce-here input-regular">{!! $article->description_ru !!}</textarea>
                        </div>
                    </div>
                    <div>
                        <div class="input-group">
                            <label class="input-group__title">Атауы <span class="required">*</span></label>
                            <input type="text" name="title_kk" placeholder="Название" class="input-regular" value="{{ $article->title_kk }}">
                        </div>
                        <br>
                        <div class="input-group">
                            <div class="input-group__title">Сипаттамасы <span class="required">*</span></div>
                            <textarea name="description_kk" class="tinymce-here input-regular">{!! $article->description_kk !!}</textarea>
                        </div>
                    </div>
                    <div>
                        <div class="input-group">
                            <label class="input-group__title">Title <span class="required">*</span></label>
                            <input type="text" name="title_en" placeholder="Название" class="input-regular" value="{{ $article->title_en }}">
                        </div>
                        <br>
                        <div class="input-group">
                            <div class="input-group__title">Description <span class="required">*</span></div>
                            <textarea name="description_en" class="tinymce-here input-regular">{!!  $article->description_en !!}</textarea>
                        </div>
                    </div>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-sm-6">
                    <div class="input-group">
                        <label class="checkbox">
                            <input type="hidden" name="is_published" value="0">
                            <input type="checkbox" value="1" name="is_published" {{ $article->is_published == 1 ? 'checked' : '' }}>
                            <span>Опубликовано</span>
                        </label>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="input-group">
                        <label class="input-group__title">Дата публикации</label>
                        <label class="time">
                            <input type="text" name="published_at" value="{{ $article->published_at }}" placeholder=""
                                   class="input-regular custom-datepicker">
                        </label>
                    </div>
                </div>
            </div>
            <div class="input-group">
                    <label class="input-group__title">Для кого</label>
                    <select name="type" class="input-regular chosen" data-placeholder="" required>
                        <option value="1" {{ $article->type == '1' ? 'selected' : '' }}>Общедоступный</option>
                        <option value="2" {{ $article->type == '2' ? 'selected' : '' }}>Авторизованным</option>
                        <option value="3" {{ $article->type == '3' ? 'selected' : '' }}>Для членов МСК</option>
                    </select>
                </div>
            <br>
            <div class="input-group">
                <label class="input-group__title">Категория</label>
                <select name="category_id" class="input-regular chosen" data-placeholder="" required>
                    @foreach($categories as $category)
                        <option value="{{$category->id}}" {{ $article->category->id == $category->id ? 'selected' : '' }}>{{ $category->name }}</option>
                    @endforeach
                </select>
            </div>
            <br>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <label class="input-group__title">Фото</label>
                    <input type="file" name="image" class="form-control" placeholder="image">
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    <button type="submit" class="btn btn--green">Сохранить</button>
                    @can('article-delete')
                        <a class="btn btn-danger btn--red" href="{{ route('panel.articles.destroy', $article->id) }}"
                           onclick="event.preventDefault();
                                                     document.getElementById('delete-form').submit();" title="Удалить">Удалить
                        </a>
                    @endcan
                </div>
            </div>
        </form>
        @can('article-delete')
            <form id="delete-form" action="{{ route('panel.articles.destroy', $article->id) }}" method="POST" class="d-none">
                @csrf
                @method('DELETE')
            </form>
        @endcan
    </div>
</div>

@endsection
@section('scripts')
    <!--Only this page's scripts-->
    <script src="https://cdn.tiny.cloud/1/eutvjr9zyhc4qtchwyfwhutknw2iunsf80kiuye2fdomu2wd/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="/admin/assets/api.js"></script>
    <script src="/admin/assets/js/tinymce.js"></script>
    <!---->
@endsection

resources/views/admin/pages/categories/index.blade.php
@extends('admin.layouts.index')

@section('title', 'Новости')

@section('content')

<div class="container container-fluid">
    <div class="title-block">
        <div class="row row--multiline align-items-center">
            <div class="col-md-8">
                <h1 class="title-primary" style="margin-bottom: 0">Управление категориями</h1>
            </div>
            <div class="col-md-4 text-right-md text-right-lg">
                <div class="flex-form">
                    <div>
                        @can('article-create')
                            <a class="btn btn-success" href="{{ route('panel.articles.create') }}">Добавить новость</a>
                        @endcan
                    </div>
                </div>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <br>
    <div class="block">
        <h2 class="title-secondary">Список новостей</h2>
        <table class="table table-records">
            <colgroup>
                <col span="1" style="width: 3%;">
                <col span="1" style="width: 20%;">
                <col span="1" style="width: 10%;">
                <col span="1" style="width: 10%;">
                <col span="1" style="width: 10%;">
                <col span="1" style="width: 25%;">
            </colgroup>
            <thead>
                <tr>
                    <th>No</th>
                    <th>Название</th>
                    <th>Опубликован</th>
                    <th>Дата публикации</th>
                    <th>Категория</th>
                    <th>Для кого</th>
                    <th>Действие</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($articles as $article)
                    <tr>
                        <td>{{ $article->id }}</td>
                        <td>{{ $article->title }}</td>
                        <td>{{ $article->is_published == '1' ? 'Да' : 'Нет'}}</td>
                        <td>{{ $article->published_at ?? '-' }}</td>
                        <td>{{ $article->category->name }}</td>
                        <td>
                            @if($article->type == '1')
                                Общедоступный
                            @elseif($article->type == '2')
                                Авторизованным
                            @elseif($article->type == '3')
                                Для членов МСК
                            @endif
                        </td>
                        <td>
                            <a class="icon-btn icon-btn--green icon-eye" href="{{ route('panel.articles.show', $article->id) }}" title="Смотреть"></a>
                            @can('article-edit')
                                <a class="icon-btn icon-btn--yellow icon-edit" href="{{ route('panel.articles.edit', $article->id) }}" title="Редактировать"></a>
                            @endcan
                            @can('article-delete')
                                <a href="javascript:;" title="Удалить"
                                   onclick="document.querySelector('#model-{{ $article->id }}').submit()"
                                   class="icon-btn icon-btn--pink icon-delete"></a>
                                <form action="{{ route('panel.articles.destroy',  $article->id) }}" id="model-{{ $article->id }}" method="post">
                                    @csrf
                                    @method('DELETE')
                                </form>
                            @endcan
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        {{ $articles->appends(\Illuminate\Support\Facades\Request::except('page'))->links("vendor.pagination.admin") }}
    </div>
</div>

@endsection
@section('scripts')
    <!--Only this page's scripts-->
    <!---->
@endsection

resources/views/admin/pages/categories/show.blade.php
@extends('admin.layouts.index')

@section('title', 'Новости')

@section('content')

<div class="container container-fluid">
    <div class="title-block">
        <div class="row row--multiline align-items-center">
            <div class="col-md-8">
                <ul class="breadcrumbs">
                    <li><a href="{{ route('panel.articles.index') }}">Управление новостями</a></li>
                    <li><span>{{ $article->title }}</span></li>
                </ul>
            </div>
            <div class="col-md-4 text-right-md text-right-lg">
                <div class="flex-form">
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ route('panel.articles.index') }}">Назад</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <div class="block">
        <h2 class="title-primary">Новость</h2>
        <div class="tabs">
            <div class="mobile-dropdown">
                <div class="mobile-dropdown__title dynamic">Рус</div>
                <div class="mobile-dropdown__desc">
                    <ul class="tabs-titles">
                        <li class="active"><a href="javascript:;" title="Рус">Рус</a></li>
                        <li><a href="javascript:;" id="" title="Қаз">Қаз</a></li>
                        <li><a href="javascript:;" id="" title="Қаз">Eng</a></li>
                    </ul>
                </div>
            </div>
            <div class="tabs-contents">
                <div class="active">
                    <div class="input-group">
                        <label class="input-group__title">Название</label>
                        <input type="text" name="title_ru" placeholder="Название"
                               class="input-regular" value="{{ $article->title_ru }}" disabled>
                    </div>
                    <div class="input-group">
                        <div class="input-group__title">Описание</div>
                        <textarea name="description_ru" class="tinymce-text-here input-regular"
                                  disabled>{!! $article->description_ru !!}</textarea>
                    </div>
                </div>
                <div>
                    <div class="input-group">
                        <label class="input-group__title">Атауы</label>
                        <input type="text" name="title_kk" placeholder="Название"
                               class="input-regular" value="{{ $article->title_kk }}" disabled>
                    </div>
                    <div class="input-group">
                        <div class="input-group__title">Сипаттамасы</div>
                        <textarea name="description_kk" class="tinymce-text-here input-regular"
                                  disabled>{!! $article->description_kk !!}</textarea>
                    </div>
                </div>
                <div>
                    <div class="input-group">
                        <label class="input-group__title">Title</label>
                        <input type="text" name="title_en" placeholder="Название"
                               class="input-regular" value="{{ $article->title_en }}" disabled>
                    </div>
                    <div class="input-group">
                        <div class="input-group__title">Description</div>
                        <textarea name="description_en" class="tinymce-text-here input-regular"
                                  disabled>{!! $article->description_en !!}</textarea>
                    </div>
                </div>
            </div>
        </div>
        <div class="input-group">
            <div class="input-group__title">Фотограция</div>
            <a href="{{ $article->image }}" target="_blank">
                <img class="article-image" src="{{ $article->image ?? ''}}" height="200" length="400">
            </a>
        </div>
        <div class="input-group">
            <label class="input-group__title">Опубликован</label>
            <input type="text" name="is_published" title="Опубликован" class="input-regular"
                   value="{{ $article->is_published == '1' ? 'Да' : 'Нет' }}" disabled>
        </div>
        <div class="input-group">
            <label class="input-group__title">Дата публикации</label>
            <input type="text" name="published_at" title="Опубликован" class="input-regular"
                   value="{{ $article->published_at ?? '-' }}" disabled>
        </div>
        <div class="input-group">
            <label class="input-group__title">Для кого</label>
            <input type="text" name="type" title="Для кого" class="input-regular" disabled
                   value="@if($article->type == '1') Общедоступный @elseif($article->type == '2') Авторизованным @elseif($article->type == '3') Для членов МСК @endif">
        </div>
        <div class="input-group">
            <label class="input-group__title">Категория</label>
            <input type="text" name="category" title="Категория" class="input-regular" value="{{ $article->category->name }}" disabled>
        </div>
        <br>
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                @can('article-edit')
                    <a class="btn btn-primary" href="{{ route('panel.articles.edit', $article->id) }}">Редактировать</a>
                @endcan
                @can('article-delete')
                    <a class="btn btn-danger btn--red" href="{{ route('panel.articles.destroy', $article->id) }}"
                       onclick="event.preventDefault();
                                                     document.getElementById('delete-form').submit();" title="Удалить">Удалить
                    </a>
                    <form id="delete-form" action="{{ route('panel.articles.destroy', $article->id) }}" method="POST" class="d-none">
                        @csrf
                        @method('DELETE')
                    </form>
                @endcan
            </div>
        </div>
    </div>
</div>

@endsection
@section('scripts')
    <!--Only this page's scripts-->
    <!---->
@endsection